@baseUrl = http://localhost:5041
@apiUsers = {{baseUrl}}/api/users
@contentType = application/json
@authToken = dev-secret-token

### Get all users
GET {{apiUsers}}
Accept: application/json
Authorization: Bearer {{authToken}}

### Get user by id

// Update userId accordingly to user created during testing
@userId = 5984aef3-d557-46f7-bffe-348f094f1636
GET {{apiUsers}}/{{userId}}
Accept: application/json
Authorization: Bearer {{authToken}}

### Create user
# @name createUser
POST {{apiUsers}}
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "email": "ada.lovelace@example.com",
  "fullName": "Ada Lovelace"
}

### Update user
# @name updateUser
PUT {{apiUsers}}/{{userId}}
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "email": "ada.updated@example.com",
  "fullName": "Ada Love"
}

### Delete user
# @name deleteUser
DELETE {{apiUsers}}/{{userId}}
Accept: application/json
Authorization: Bearer {{authToken}}

### Redirect to Swagger UI
GET {{baseUrl}}/
Accept: text/html
Authorization: Bearer {{authToken}}
